### ISSUE TITLE
One Side Open does not create even height sides

### ISSUE THREAD

**Issue by alexbbrown** [paulh-rnd/TabbedBoxMaker#20] opened 2018-03-05 04:47 UTC
This may be intentional, but unexpected for me: "One Side Open" (with other settings attached) with "Diag Alternate Tabs" creates a box whose smooth top edges are not all at the same height.

<img width="309" alt="screen shot 2018-03-04 at 20 41 30" src="https://user-images.githubusercontent.com/2532344/36957870-7a9a30e2-1fec-11e8-8b77-522227c097b8.png">

![img_0482](https://user-images.githubusercontent.com/2532344/36957874-8141f9d4-1fec-11e8-9963-da128a7f8004.JPG)

**Comment by paulh-rnd** [comment] 2018-03-05 05:32
Not intentional! Thanks for reporting, I'll check it out.

>

**Comment by paulh-rnd** [comment] 2018-07-17 04:23
Hey, thanks again for reporting this issue.  Sorry I haven't had a chance to work on it yet, it's been a hectic few months.  I'll hopefully get the chance to work on this in the next few weeks.

Nice pot for your succulents, btw.

**Comment by paulh-rnd** [comment] 2020-06-03 14:02
Hey, just letting you know that I've just released a new (beta) version that is compatible with Inkscape v1.0.  I can't reproduce this exact problem, however I do see another issue when using the new Rotate Symmetric option.  I'll close this for now but if you can reproduce it in the latest version feel free to reopen with more details.  Thanks.

**Closed by paulh-rnd** 2020-06-03 14:02 UTC
Labels: bug
