### ISSUE TITLE
AttributeError: 'module' object has no attribute 'unittouu'

### ISSUE THREAD

**Issue by kmishaque** [paulh-rnd/TabbedBoxMaker#18] opened 2017-11-27 15:53 UTC
Hi,

When I try and make a MI GRBL Z AXIS Servo Controller , I get the following error:

Traceback (most recent call last):
  File "servo.py", line 3172, in <module>
    e.affect()     
  File "inkex.py", line 283, in affect
    self.effect()
  File "servo.py", line 3156, in effect
    self.orientation( self.layers[min(0,len(self.layers)-1)] )        
  File "servo.py", line 3085, in orientation
    doc_height = inkex.unittouu(self.document.getroot().get('height'))

running in windows 7, inkscape v0.92.2 pre release

**Comment by paulh-rnd** [comment] 2017-11-27 19:57
Thanks for this report. It has been a while since I've looked at this extension and it looks like the good team at Inkscape have broken the unittouu function again. Last break was the 0.91 release.

Good news is this shouldn't be hard to fix, bad news is I have no time at all this week to fix it and run tests.

If you want to try and patch it yourself, according to this page all you need to do is remove the "inkex." prefix each time unittouu is called:

https://github.com/sambody/inkscape-guide-tools/issues/9

It would be nice to maintain compatibility with 0.91 though this is not a high priority.

**Comment by applemuncy** [comment] 2017-11-28 13:46
Panour in closed issue 16 reports that Inkscape 0.92 work.
Perhaps just downgrading from 0.92.2pre-release is a reasonable quick fix.

**Comment by rkolibar** [comment] 2018-11-05 05:55
Thanks @mburakkalkan Now i have this error:

File "servo.py", line 3087
    doc_height = 1052.3622047
    ^
IndentationError: unexpected indent

**Comment by ProfeRamon46** [comment] 2019-08-17 16:21
I have tried...
doc_height = self.unittouu(self.document.getroot().get('height'))
and 
doc_height = self.unittouu(self.document.getroot().xpath('@height', namespaces=inkex.NSS)[0])
and none works

**Comment by paulh-rnd** [comment] 2020-01-03 10:22
OK, apologies for taking more than *2 years* to look at this, in spite of my earlier promises...  But I've actually looked at it this time - more than my previous brief scan - and I'm actually not sure why this bug was logged here.  It's not a bug with the TabbedBoxMaker (although it looks similar to one we've dealt with in the past, which is why I replied as I did originally).  I'm going to close this as I can't see any way to help other than the suggestions that have already been given.  If you need more information please reach out to the author(s) of the *MI GRBL Z AXIS Servo Controller* to ask them for support.

Thanks

**Closed by paulh-rnd** 2020-01-03 10:22 UTC
Labels: bug
